# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm install && cd backend && npm install"]

[phases.build]
cmds = [
    "cd backend && node scripts/setup-prisma.js",
    "cd backend && npx prisma generate",
    "cd backend && npm run build"
]

[start]
cmd = "cd backend && npx prisma migrate deploy && npm start"

[variables]
NODE_ENV = "production"