services:
  # Backend API
  - type: web
    name: tea-inventory-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tea-inventory-db
          property: connectionString

  # Frontend
  - type: web  
    name: tea-inventory-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://tea-inventory-backend.onrender.com/api

# Database
databases:
  - name: tea-inventory-db
    plan: starter # $7/month